name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up Scala & sbt
      uses: olafurpg/setup-scala@v11
      with:
        scala-version: '3.7.0'
        sbt-version: '1.11.0'
    - name: Run tests
      run: sbt test